### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by h3xstream** [victims/victims-web#135] opened 2015-02-16 19:26 UTC
When visiting https://victi.ms/ or when using the enforcer plugin, the website return an error message.

    503 Service Unavailable
    No server is available to handle this request.

**Comment by abn** [comment] 2015-02-17 01:09
This has been resolved in production. Root cause is some unknown resource capping on OpenShift gears.

**Closed by abn** 2015-02-17 01:09 UTC
